import type { Course, CourseModule, Specialty, Trainer } from "@/types/course";

export const SPECIALTIES: Specialty[] = [
  { id: "tech", name: "تقنية وبرمجة", slug: "tech" },
  { id: "ai", name: "ذكاء اصطناعي", slug: "ai" },
  { id: "design", name: "تصميم وإبداع", slug: "design" },
  { id: "business", name: "أعمال وريادة", slug: "business" },
  { id: "marketing", name: "تسويق رقمي", slug: "marketing" },
  { id: "accounting", name: "محاسبة ومالية", slug: "accounting" },
  { id: "languages", name: "لغات", slug: "languages" },
  { id: "media", name: "إعلام ومحتوى", slug: "media" },
  { id: "education", name: "تعليم وتدريب", slug: "education" },
  { id: "engineering", name: "هندسة ومشاريع", slug: "engineering" },
  { id: "law", name: "قانون وامتثال", slug: "law" },
  { id: "health", name: "صحة وعافية", slug: "health" },
  { id: "personal", name: "تطوير ذاتي", slug: "personal" },
];

export const TRAINERS: Trainer[] = [
  {
    id: "t1",
    name: "د. نورة الحربي",
    title: "مهندسة برمجيات ومدربة تقنية",
    bio: "تركّز على بناء مهارات عملية في تطوير الويب والتفكير الحاسوبي للمبتدئين.",
  },
  {
    id: "t2",
    name: "أحمد الزهراني",
    title: "محلل بيانات",
    bio: "يساعد المتعلمين على فهم البيانات واتخاذ قرارات مبنية على تحليل واضح.",
  },
  {
    id: "t3",
    name: "ليان العبدالله",
    title: "مصممة تجربة مستخدم",
    bio: "تدمج بين التصميم البصري وفهم سلوك المستخدم لبناء منتجات رقمية مفهومة.",
  },
  {
    id: "t4",
    name: "فهد القحطاني",
    title: "مستشار أعمال",
    bio: "يركّز على ريادة الأعمال والمهارات المالية للمحترفين ورواد المشاريع.",
  },
  {
    id: "t5",
    name: "مريم الشمري",
    title: "مدربة لغات",
    bio: "تقدّم مسارات تعلّم لغة إنجليزية مهنية بأسلوب تفاعلي ومرن.",
  },
  {
    id: "t6",
    name: "يوسف الدوسري",
    title: "مدرب تطوير ذاتي",
    bio: "يساعد المتعلمين على بناء عادات تعلّم مستدامة وإدارة الوقت بفعالية.",
  },
  {
    id: "t7",
    name: "د. سارة المنصور",
    title: "باحثة في الذكاء الاصطناعي",
    bio: "تبسّط مفاهيم AI وتعلّم الآلة للمتخصصين غير التقنيين والمطورين على حد سواء.",
  },
  {
    id: "t8",
    name: "رنيم العتيبي",
    title: "استشارية تسويق رقمي",
    bio: "تعمل على بناء حملات محتوى وإعلانات رقمية تحقّق نتائج قابلة للقياس.",
  },
  {
    id: "t9",
    name: "خالد المطيري",
    title: "محاسب قانوني",
    bio: "يشرّح المحاسبة والضرائب للأفراد والمنشآت الصغيرة بلغة واضحة.",
  },
  {
    id: "t10",
    name: "هند السبيعي",
    title: "صانعة محتوى",
    bio: "تعلّم صناعة فيديوهات ومنشورات احترافية للمنصات العربية.",
  },
  {
    id: "t11",
    name: "د. عمر البلوي",
    title: "مختص تربية وتعليم",
    bio: "يركّز على طرق التدريس الحديثة وتصميم تجارب تعلّم فعّالة.",
  },
  {
    id: "t12",
    name: "Eng. منى الغامدي",
    title: "مهندسة مشاريع",
    bio: "تدرب على إدارة المشاريع الهندسية وفهم أساسيات PMI بأسلوب عملي.",
  },
  {
    id: "t13",
    name: "المحامية نجلاء الحارثي",
    title: "مستشارة قانونية",
    bio: "تشرح العقود والامتثال للأعمال والأفراد دون تعقيد قانوني زائد.",
  },
  {
    id: "t14",
    name: "د. ليلى القرني",
    title: "أخصائية صحة نفسية",
    bio: "تقدّم مسارات للتوازن النفسي وإدارة الضغط في العمل والدراسة.",
  },
];

function buildSyllabus(course: Omit<Course, "syllabus">): CourseModule[] {
  const lessonCount = course.goals.length * 2;
  const totalMinutes = course.hours * 60;
  const baseDuration = Math.floor(totalMinutes / lessonCount);
  let remainingMinutes = totalMinutes - baseDuration * lessonCount;

  return course.goals.map((goal, moduleIndex) => {
    const makeLesson = (kind: "concept" | "practice") => {
      const durationMinutes = baseDuration + (remainingMinutes-- > 0 ? 1 : 0);
      const isConcept = kind === "concept";
      return {
        id: `${course.id}-m${moduleIndex + 1}-${isConcept ? "concept" : "practice"}`,
        title: isConcept ? `فهم ${goal}` : `تطبيق ${goal}`,
        durationMinutes,
        outcomes: [
          isConcept ? `شرح عناصر ${goal} بلغة واضحة` : `تنفيذ تمرين عملي يثبت القدرة على ${goal}`,
        ],
      };
    };

    return {
      id: `${course.id}-module-${moduleIndex + 1}`,
      title: goal,
      outcomes: [goal],
      lessons: [makeLesson("concept"), makeLesson("practice")],
    };
  });
}

function withSyllabus(course: Omit<Course, "syllabus">): Course {
  return { ...course, syllabus: buildSyllabus(course) };
}

export const COURSES: Course[] = ([
  {
    id: "c1",
    slug: "web-foundations",
    title: "أساسيات تطوير الويب",
    summary: "ابنِ أول موقع تفاعلي وافهم HTML و CSS و JavaScript من الصفر.",
    description:
      "دورة تأسيسية تأخذك خطوة بخطوة في عالم تطوير الويب. ستتعلّم بناء صفحات منظمة، تنسيقها باحتراف، وإضافة تفاعل بسيط — مع مشروع عملي تخرج به في نهاية المسار.",
    specialtyId: "tech",
    trainerId: "t1",
    level: "beginner",
    deliveryMode: "recorded",
    hours: 12,
    goals: ["فهم بنية صفحات الويب", "بناء مشروع Portfolio بسيط", "الاستعداد لمسارات Front-end"],
    prerequisites: ["لا يلزم خبرة برمجية سابقة"],
    hasCertificate: true,
    matchTags: ["career_change", "student", "beginner", "tech"],
  },
  {
    id: "c2",
    slug: "react-practical",
    title: "React عملي للمشاريع",
    summary: "تعلّم بناء واجهات حديثة بمكوّنات قابلة لإعادة الاستخدام.",
    description:
      "مسار يركّز على التطبيق العملي لـ React: حالة المكوّنات، ربط API، وتنظيم مشروع حقيقي. مناسب لمن يريد الانتقال من الأساسيات إلى بناء تطبيقات.",
    specialtyId: "tech",
    trainerId: "t1",
    level: "intermediate",
    deliveryMode: "hybrid",
    hours: 18,
    goals: ["بناء تطبيق React كامل", "فهم إدارة الحالة", "التجهيز لسوق العمل"],
    prerequisites: ["أساسيات JavaScript", "HTML/CSS"],
    hasCertificate: true,
    matchTags: ["career_change", "skill_upgrade", "intermediate", "tech"],
  },
  {
    id: "c3",
    slug: "data-analysis-intro",
    title: "مقدمة في تحليل البيانات",
    summary: "اقرأ البيانات، نظّفها، واستخرج منها رؤى مفيدة.",
    description:
      "تعلّم دورة تحليل البيانات من منظور عملي: جمع البيانات، التنظيف، الرسوم البيانية، وصياغة استنتاجات — بدون تعقيد غير ضروري.",
    specialtyId: "tech",
    trainerId: "t2",
    level: "beginner",
    deliveryMode: "recorded",
    hours: 10,
    goals: ["فهم دورة حياة البيانات", "إنشاء تقارير بصرية", "دعم قراراتك المهنية"],
    prerequisites: ["مهارات حاسوب أساسية"],
    hasCertificate: true,
    matchTags: ["career_change", "skill_upgrade", "student", "beginner", "tech"],
  },
  {
    id: "c4",
    slug: "ux-design-fundamentals",
    title: "أساسيات تصميم تجربة المستخدم",
    summary: "صمّم منتجات رقمية مفهومة وسهلة الاستخدام.",
    description:
      "من البحث عن المستخدم إلى النماذج الأولية — دورة تشرح UX بأسلوب واضح مع تمارين على مشكلات حقيقية.",
    specialtyId: "design",
    trainerId: "t3",
    level: "beginner",
    deliveryMode: "live",
    hours: 14,
    goals: ["فهم رحلة المستخدم", "بناء Wireframes", "تقديم تصاميم مدعومة بمنطق"],
    prerequisites: ["اهتمام بالتصميم — لا يلزم خبرة"],
    hasCertificate: true,
    matchTags: ["career_change", "personal", "beginner", "design"],
  },
  {
    id: "c5",
    slug: "visual-identity",
    title: "الهوية البصرية للمشاريع",
    summary: "ابنِ هوية متسقة من الألوان والخطوط إلى التطبيق.",
    description:
      "دورة للمصممين والمؤسسين معًا — تتعلّم كيف تبني هوية بصرية تعكس رسالة المشروع وتعمل عبر المنصات.",
    specialtyId: "design",
    trainerId: "t3",
    level: "intermediate",
    deliveryMode: "recorded",
    hours: 8,
    goals: ["بناء Moodboard", "تصميم نظام بصري", "تطبيق الهوية على assets"],
    prerequisites: ["أساسيات التصميم"],
    hasCertificate: false,
    matchTags: ["skill_upgrade", "personal", "intermediate", "design"],
  },
  {
    id: "c6",
    slug: "startup-essentials",
    title: "أساسيات بناء مشروعك",
    summary: "من الفكرة إلى نموذج عمل قابل للاختبار.",
    description:
      "مسار يساعدك على هيكلة فكرتك، فهم السوق، وبناء عرض قيمة — بخطوات عملية مناسبة للمبتدئين في ريادة الأعمال.",
    specialtyId: "business",
    trainerId: "t4",
    level: "beginner",
    deliveryMode: "hybrid",
    hours: 11,
    goals: ["صياغة Value Proposition", "فهم نموذج العمل", "إعداد خطة اختبار أولى"],
    prerequisites: ["لا يلزم خبرة سابقة"],
    hasCertificate: true,
    matchTags: ["career_change", "personal", "beginner", "business"],
  },
  {
    id: "c7",
    slug: "financial-literacy",
    title: "الثقافة المالية للمحترفين",
    summary: "افهم الميزانية، الادخار، والاستثمار على مستواك.",
    description:
      "دورة عملية تساعدك على إدارة دخلك، بناء احتياطي، وفهم مبادئ الاستثمار بدون jargon مبالغ فيه.",
    specialtyId: "business",
    trainerId: "t4",
    level: "intermediate",
    deliveryMode: "recorded",
    hours: 7,
    goals: ["بناء ميزانية شخصية", "فهم المخاطر والعوائد", "قرارات مالية أوضح"],
    prerequisites: ["دخل منتظم (وظيفة أو عمل حر)"],
    hasCertificate: false,
    matchTags: ["skill_upgrade", "personal", "intermediate", "business"],
  },
  {
    id: "c8",
    slug: "english-for-work",
    title: "إنجليزي مهني للتواصل",
    summary: "عزّز لغتك في الاجتماعات والبريد والمقابلات.",
    description:
      "مسار مركّز على مواقف العمل اليومية: كتابة رسائل احترافية، التحدث في اجتماعات، والاستعداد للمقابلات.",
    specialtyId: "languages",
    trainerId: "t5",
    level: "intermediate",
    deliveryMode: "live",
    hours: 16,
    goals: ["ثقة أعلى في المحادثة", "كتابة emails احترافية", "تحضير للمقابلات"],
    prerequisites: ["مستوى إنجليزي متوسط"],
    hasCertificate: true,
    matchTags: ["career_change", "skill_upgrade", "student", "intermediate", "languages"],
  },
  {
    id: "c9",
    slug: "learning-habits",
    title: "عادات التعلّم المستدام",
    summary: "تعلّم كيف تتعلّم — بوتيرة تناسب حياتك.",
    description:
      "دورة قصيرة عن بناء نظام تعلّم شخصي: التخطيط الأسبوعي، التركيز، ومراجععة ما تتعلّمه — مثالية قبل أي مسار آخر.",
    specialtyId: "personal",
    trainerId: "t6",
    level: "beginner",
    deliveryMode: "recorded",
    hours: 5,
    goals: ["خطة تعلّم أسبوعية", "تقليل المشتتات", "متابعة التقدّم"],
    prerequisites: ["لا يلزم خبرة"],
    hasCertificate: false,
    matchTags: ["student", "personal", "beginner", "personal"],
  },
  {
    id: "c10",
    slug: "advanced-js-patterns",
    title: "أنماط JavaScript المتقدمة",
    summary: "عمّق فهمك للغة وبنى الكود القابل للصيانة.",
    description:
      "للمبرمجين الذين يريدون الانتقال من «يعمل» إلى «كود نظيف»: closures، async patterns، وتنظيم modules.",
    specialtyId: "tech",
    trainerId: "t1",
    level: "advanced",
    deliveryMode: "recorded",
    hours: 15,
    goals: ["كتابة كود قابل للصيانة", "فهم async/deep JS", "الاستعداد لمشاريع أكبر"],
    prerequisites: ["JavaScript متوسط", "خبرة مشروع واحد على الأقل"],
    hasCertificate: true,
    matchTags: ["skill_upgrade", "advanced", "tech"],
  },
  {
    id: "c11",
    slug: "ai-for-beginners",
    title: "مقدمة في الذكاء الاصطناعي",
    summary: "افهم AI وتعلّم الآلة واستخداماته العملية دون خلفية تقنية.",
    description:
      "دورة تأسيسية تشرح ما هو الذكاء الاصطناعي، كيف يعمل، وأين يُستخدم اليوم — مع أمثلة عربية من التعليم والأعمال.",
    specialtyId: "ai",
    trainerId: "t7",
    level: "beginner",
    deliveryMode: "recorded",
    hours: 8,
    goals: ["فهم مفاهيم AI الأساسية", "التعرّف على أدوات ChatGPT وGemini", "تحديد فرص الاستخدام"],
    prerequisites: ["لا يلزم خبرة برمجية"],
    hasCertificate: true,
    matchTags: ["career_change", "student", "beginner", "tech"],
  },
  {
    id: "c12",
    slug: "prompt-engineering",
    title: "هندسة الأوامر للمحترفين",
    summary: "اكتب prompts فعّالة لتحليل، كتابة، وبرمجة أسرع.",
    description:
      "مسار عملي لاستخدام نماذج اللغة في العمل اليومي: صياغة أوامر، تقييم النتائج، وبناء workflows بسيطة.",
    specialtyId: "ai",
    trainerId: "t7",
    level: "intermediate",
    deliveryMode: "hybrid",
    hours: 6,
    goals: ["كتابة prompts احترافية", "أتمتة مهام متكررة", "تقليل وقت العمل"],
    prerequisites: ["استخدام أساسي لأدوات AI"],
    hasCertificate: false,
    matchTags: ["skill_upgrade", "intermediate", "tech"],
  },
  {
    id: "c13",
    slug: "digital-marketing-basics",
    title: "أساسيات التسويق الرقمي",
    summary: "من الخطة إلى التنفيذ — SEO، محتوى، وإعلانات مدفوعة.",
    description:
      "تعلّم كيف تبني حضورًا رقميًا: فهم الجمهور، إنشاء محتوى، وقياس الأداء عبر المنصات الشائعة.",
    specialtyId: "marketing",
    trainerId: "t8",
    level: "beginner",
    deliveryMode: "recorded",
    hours: 12,
    goals: ["بناء خطة تسويق", "فهم SEO الأساسي", "إطلاق حملة مدفوعة بسيطة"],
    prerequisites: ["لا يلزم خبرة"],
    hasCertificate: true,
    matchTags: ["career_change", "skill_upgrade", "beginner", "business"],
  },
  {
    id: "c14",
    slug: "social-media-strategy",
    title: "استراتيجية المحتوى على المنصات",
    summary: "جدولة، تحليل، ونمو — لحسابات الأفراد والعلامات.",
    description:
      "دورة مركّزة على Instagram وX وLinkedIn: صناعة محتوى جذّاب، التفاعل، وتحويل المتابعين إلى عملاء.",
    specialtyId: "marketing",
    trainerId: "t8",
    level: "intermediate",
    deliveryMode: "live",
    hours: 9,
    goals: ["تقويم محتوى شهري", "تحليل المقاييس", "بناء هوية رقمية"],
    prerequisites: ["حساب نشط على منصة واحدة على الأقل"],
    hasCertificate: false,
    matchTags: ["skill_upgrade", "personal", "intermediate", "business"],
  },
  {
    id: "c15",
    slug: "accounting-fundamentals",
    title: "أساسيات المحاسبة للمنشآت الصغيرة",
    summary: "قيود، ميزانية، وتقارير — بلغة غير محاسبية.",
    description:
      "مسار يشرح الدورة المحاسبية، الميزانية العمومية، وقائمة الدخل للمؤسسين والموظفين في الشركات الناشئة.",
    specialtyId: "accounting",
    trainerId: "t9",
    level: "beginner",
    deliveryMode: "recorded",
    hours: 10,
    goals: ["قراءة التقارير المالية", "فهم القيود الأساسية", "التواصل مع المحاسب"],
    prerequisites: ["لا يلزم خبرة محاسبية"],
    hasCertificate: true,
    matchTags: ["career_change", "skill_upgrade", "beginner", "business"],
  },
  {
    id: "c16",
    slug: "zakat-tax-basics",
    title: "زكاة وضرائب — مبادئ للأفراد",
    summary: "افهم التزاماتك المالية الرسمية بوضوح.",
    description:
      "دورة مختصرة عن الزكاة والضريبة والإقرارات للأفراد وأصحاب الأعمال الصغيرة في السياق المحلي.",
    specialtyId: "accounting",
    trainerId: "t9",
    level: "intermediate",
    deliveryMode: "recorded",
    hours: 5,
    goals: ["فهم الزكاة والضريبة", "تجنّب الأخطاء الشائعة", "التخطيط المالي"],
    prerequisites: ["دخل أو نشاط تجاري"],
    hasCertificate: false,
    matchTags: ["personal", "skill_upgrade", "intermediate", "business"],
  },
  {
    id: "c17",
    slug: "content-creation-video",
    title: "صناعة محتوى فيديو",
    summary: "من الفكرة إلى النشر — تصوير، مونتاج، وعناوين.",
    description:
      "تعلّم إنتاج فيديوهات قصيرة احترافية للتعليم والتسويق باستخدام أدوات متاحة ومجانية.",
    specialtyId: "media",
    trainerId: "t10",
    level: "beginner",
    deliveryMode: "hybrid",
    hours: 11,
    goals: ["كتابة سيناريو", "مونتاج أساسي", "تحسين العناوين والوصف"],
    prerequisites: ["هاتف أو كاميرا بسيطة"],
    hasCertificate: true,
    matchTags: ["career_change", "personal", "beginner", "design"],
  },
  {
    id: "c18",
    slug: "podcast-arabic",
    title: "إطلاق بودكاست عربي",
    summary: "ابدأ برنامجك الصوتي من الصفر حتى أول 10 حلقات.",
    description:
      "مسار شامل: اختيار الفكرة، التسجيل، التحرير، والنشر على المنصات مع بناء جمهور أولي.",
    specialtyId: "media",
    trainerId: "t10",
    level: "intermediate",
    deliveryMode: "recorded",
    hours: 8,
    goals: ["إعداد استوديو منزلي", "تحرير صوتي", "استراتيجية نشر"],
    prerequisites: ["موضوع أو فكرة للبرنامج"],
    hasCertificate: false,
    matchTags: ["personal", "skill_upgrade", "intermediate", "business"],
  },
  {
    id: "c19",
    slug: "modern-teaching",
    title: "التدريس الحديث والتعلّم النشط",
    summary: "حوّل حصصك إلى تجربة تفاعلية تحفّز المتعلّم.",
    description:
      "دورة للمعلّمين والمدربين: استراتيجيات التعلّم النشط، التقييم، واستخدام التقنية في الصف.",
    specialtyId: "education",
    trainerId: "t11",
    level: "intermediate",
    deliveryMode: "live",
    hours: 14,
    goals: ["تصميم أنشطة تفاعلية", "تقييم عادل", "دمج أدوات رقمية"],
    prerequisites: ["خبرة تدريس أو تدريب"],
    hasCertificate: true,
    matchTags: ["skill_upgrade", "student", "intermediate", "personal"],
  },
  {
    id: "c20",
    slug: "curriculum-design",
    title: "تصميم مناهج ومسارات تعلّم",
    summary: "ابنِ مسارًا تعليميًا متسلسلًا من الأهداف إلى التقييم.",
    description:
      "للمدربين وصنّاع الدورات: تحليل الاحتياج، كتابة الأهداف، وتقسيم المحتوى إلى وحدات قابلة للاستهلاك.",
    specialtyId: "education",
    trainerId: "t11",
    level: "advanced",
    deliveryMode: "hybrid",
    hours: 12,
    goals: ["تحليل احتياجات المتعلّم", "بناء outline احترافي", "تصميم تقييمات"],
    prerequisites: ["خبرة في مجال تريد تدريبه"],
    hasCertificate: true,
    matchTags: ["career_change", "skill_upgrade", "advanced", "personal"],
  },
  {
    id: "c21",
    slug: "project-management-pmi",
    title: "أساسيات إدارة المشاريع",
    summary: "PMI مبسّط — نطاق، جدول، مخاطر، وأصحاب مصلحة.",
    description:
      "دورة تطبيقية لإدارة المشاريع في الهندسة والتقنية والأعمال، مع قوالب جاهزة للاستخدام.",
    specialtyId: "engineering",
    trainerId: "t12",
    level: "intermediate",
    deliveryMode: "recorded",
    hours: 16,
    goals: ["خطة مشروع كاملة", "إدارة المخاطر", "التنسيق مع الفريق"],
    prerequisites: ["خبرة عمل أو مشروع سابق"],
    hasCertificate: true,
    matchTags: ["career_change", "skill_upgrade", "intermediate", "business"],
  },
  {
    id: "c22",
    slug: "autocad-basics",
    title: "AutoCAD للمبتدئين",
    summary: "ارسم مخطّطات ثنائية الأبعاد بثقة.",
    description:
      "مسار تأسيسي في الرسم الهندسي الرقمي: أوامر أساسية، طبقات، وطباعة — مناسب للطلاب والمهندسين الجدد.",
    specialtyId: "engineering",
    trainerId: "t12",
    level: "beginner",
    deliveryMode: "recorded",
    hours: 13,
    goals: ["رسم مخطّط بسيط", "استخدام Layers", "تجهيز ملف للطباعة"],
    prerequisites: ["لا يلزم خبرة CAD"],
    hasCertificate: true,
    matchTags: ["student", "career_change", "beginner", "tech"],
  },
  {
    id: "c23",
    slug: "contracts-101",
    title: "العقود للأعمال — مبادئ",
    summary: "اقرأ العقد، افهم بنوده، وناقش بثقة.",
    description:
      "دورة غير قانونية بحتة بل عملية: بنود شائعة، مخاطر، ونقاط تفاوض للموظفين وأصحاب المشاريع.",
    specialtyId: "law",
    trainerId: "t13",
    level: "beginner",
    deliveryMode: "recorded",
    hours: 7,
    goals: ["قراءة عقد عمل", "التعرّف على البنود الخطرة", "أسئلة للمحامي"],
    prerequisites: ["لا يلزم خبرة قانونية"],
    hasCertificate: false,
    matchTags: ["career_change", "skill_upgrade", "beginner", "business"],
  },
  {
    id: "c24",
    slug: "labor-law-essentials",
    title: "أساسيات نظام العمل",
    summary: "حقوق وواجبات — للموظّفين ومديري HR.",
    description:
      "شرح مبسّط لأهم مواد نظام العمل: عقود، إجازات، نهاية خدمة، والامتثال في المنشآت.",
    specialtyId: "law",
    trainerId: "t13",
    level: "intermediate",
    deliveryMode: "live",
    hours: 9,
    goals: ["فهم الحقوق الأساسية", "سياسات HR أوضح", "تقليل النزاعات"],
    prerequisites: ["عمل في قطاع خاص أو HR"],
    hasCertificate: true,
    matchTags: ["skill_upgrade", "intermediate", "business"],
  },
  {
    id: "c25",
    slug: "stress-management",
    title: "إدارة الضغط والتوازن",
    summary: "تقنيات عملية للتركيز والهدوء في العمل والدراسة.",
    description:
      "دورة قصيرة عن التنفّس، التخطيط، وحدود العمل — لمن يواجه burnout أو ضغطًا مستمرًا.",
    specialtyId: "health",
    trainerId: "t14",
    level: "beginner",
    deliveryMode: "recorded",
    hours: 5,
    goals: ["تقنيات تهدئة فورية", "روتين أسبوعي متوازن", "تحديد الأولويات"],
    prerequisites: ["لا يلزم خبرة"],
    hasCertificate: false,
    matchTags: ["personal", "student", "beginner", "personal"],
  },
  {
    id: "c26",
    slug: "mindfulness-work",
    title: "اليقظة الذهنية للمحترفين",
    summary: "مارس الانتباه الواعي دون مبالغة روحانية.",
    description:
      "مسار علمي مبسّط: تمارين يومية قصيرة لتحسين التركيز، النوم، والعلاقات في بيئة العمل.",
    specialtyId: "health",
    trainerId: "t14",
    level: "intermediate",
    deliveryMode: "hybrid",
    hours: 6,
    goals: ["تمرين يومي 10 دقائق", "تقليل القلق", "تحسين جودة النوم"],
    prerequisites: ["لا يلزم خبرة"],
    hasCertificate: false,
    matchTags: ["personal", "skill_upgrade", "intermediate", "personal"],
  },
  {
    id: "c27",
    slug: "arabic-for-non-native",
    title: "العربية للناطقين بغيرها",
    summary: "أساسيات المحادثة والقراءة للمبتدئين.",
    description:
      "مسار تفاعلي لتعلّم العربية الفصحى المبسّطة: حروف، مفردات يومية، ومحادثات قصيرة.",
    specialtyId: "languages",
    trainerId: "t5",
    level: "beginner",
    deliveryMode: "live",
    hours: 20,
    goals: ["قراءة بسيطة", "محادثة يومية", "فهم النطق"],
    prerequisites: ["لا يلزم معرفة مسبقة"],
    hasCertificate: true,
    matchTags: ["student", "personal", "beginner", "languages"],
  },
  {
    id: "c28",
    slug: "public-speaking",
    title: "فن الإلقاء والتحدّث أمام الجمهور",
    summary: "تغلّب على الخوف وقدّم عرضًا واثقًا.",
    description:
      "دورة عملية: بنية العرض، لغة الجسد، والتعامل مع الأسئلة — للاجتماعات والمقابلات والمناسبات.",
    specialtyId: "personal",
    trainerId: "t6",
    level: "intermediate",
    deliveryMode: "live",
    hours: 8,
    goals: ["عرض 5 دقائق واثق", "تقليل التوتر", "استخدام Slides بفعالية"],
    prerequisites: ["لا يلزم خبرة"],
    hasCertificate: true,
    matchTags: ["career_change", "skill_upgrade", "intermediate", "personal"],
  },
] satisfies Omit<Course, "syllabus">[]).map(withSyllabus);

export function getTrainerById(id: string) {
  return TRAINERS.find((trainer) => trainer.id === id);
}

export function getSpecialtyById(id: string) {
  return SPECIALTIES.find((specialty) => specialty.id === id);
}

export function getCourseBySlug(slug: string) {
  return COURSES.find((course) => course.slug === slug);
}
